server:
  port: 8084

spring:
   profiles: dev
  # 指定当前微服务对外(提供者)暴露的名称
  application:
    name: kkbmsc-provider-depart

spring:
  jpa:
    # 应用启动时是否自动建表，默认为false
    generate-ddl: true
    # 是否在控制台显示SQL语句，默认为false
    show-sql: true
    # 设置应用启动时不重新建表
    hibernate:
      ddl-auto: none

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test02?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root

eureka:
  client:
    service-url: # 指定Eureka服务注册中心
      defaultZone: http://eureka8400.com:8400/eureka
